name: Upstream Sync
on:
  workflow_dispatch:
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: AxoniusTK/sync_test_dest
      - name: Reset the default branch with upstream changes
        run: |
          git remote add upstream https://github.com/TalKatz1/sync_test_source.git
          git fetch upstream main:upstream-main
          git reset --hard upstream-main
          git fetch upstream --tags
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          branch: upstream-changes
